ai:
  api_key: ''
  base_url: http://localhost:11434/
  enabled: true
  model: ollama3.1
  provider: ollama
auth:
  credentials:
    password: test
    username: test
  enabled: true
  selectors:
    login_url: http://testphp.vulnweb.com/login.php
    password_field: password
    submit_button: login
    success_indicator: http://testphp.vulnweb.com/userinfo.php
    username_field: username
  type: form
output:
  directory: report1
  formats:
  - html
  - json
scan:
  modules:
  - injection
  - xss
  - sensitive_data
  - misconfig
  - upload
  - api
  - idor
  - csrf
  - privesc
  rate_limit: 10
  timeout: 30
target:
  scope: ''
  url: http://testphp.vulnweb.com
